"""The ``.adventure-call/`` store: a project's analysis, kept beside it (tic-49da).

``adventure-call init`` creates the store at a project root and ``update``
refreshes it; every query command finds it by walking up from the current
directory, the way git finds ``.git``.  The store holds:

==================  ==========================================================
config.json         the analysis options, so ``update`` reruns the same run
manifest.json       source path -> mtime when last analysed (staleness check)
codebase_graph.json the node-link graph (see writer.py)
symbol_registry.json full symbol detail
AGENTS.md           how an agent uses the CLI; regenerated on every update
.gitignore          keeps the generated JSON out of git
==================  ==========================================================
"""

from __future__ import annotations

import json
import os
import subprocess
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

from adventure_call import __version__
from adventure_call.graph import GraphBuilder
from adventure_call.parser import DEFAULT_MAX_FILE_BYTES, CodebaseParser
from adventure_call.resolver import SymbolResolver
from adventure_call.writer import OutputWriter

STORE_DIRNAME = ".adventure-call"
CONFIG_FILENAME = "config.json"
MANIFEST_FILENAME = "manifest.json"
AGENTS_FILENAME = "AGENTS.md"

_GITIGNORE = """\
# Generated by adventure-call. config.json and AGENTS.md are worth committing;
# the analysis itself is rebuilt by `adventure-call update`.
*.json
!config.json
"""


class StoreError(Exception):
    """No store, or a store that cannot be used."""


@dataclass
class AnalysisOptions:
    """Everything that shapes an analysis run; persisted in config.json."""

    strip_prefix: str = ""
    module_prefix: str | None = None
    exclude: list[str] = field(default_factory=list)
    exclude_dir: list[str] = field(default_factory=list)
    max_file_bytes: int = DEFAULT_MAX_FILE_BYTES
    no_source: bool = False
    no_heuristic: bool = False
    # Stores include module-level calls so entry-point scripts remain visible
    # to agent queries.  The one-shot `analyze` command explicitly retains its
    # historical False default for the web call-flow view.
    module_calls: bool = True
    contains_edges: bool = False
    external_imports: bool = False

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "AnalysisOptions":
        known = {k: v for k, v in data.items() if k in cls.__dataclass_fields__}
        return cls(**known)


@dataclass
class AnalysisResult:
    stats: dict[str, Any]
    written: dict[str, Path]
    parsed_files: list
    builder: GraphBuilder
    seconds: float


def analyse(root: Path, options: AnalysisOptions, out_dir: Path | None) -> AnalysisResult | None:
    """Run the pipeline; write to ``out_dir`` unless it is None.

    Returns None when the root holds no parseable source.
    """
    started = time.monotonic()
    parser = _parser(root, options)
    parsed_files = parser.parse_tree()
    if not parsed_files:
        return None
    index = SymbolResolver(parsed_files, root=root).resolve()
    builder = GraphBuilder(
        parsed_files,
        index,
        include_heuristic=not options.no_heuristic,
        module_call_edges=options.module_calls,
        contains_edges=options.contains_edges,
        external_imports=options.external_imports,
    )
    graph = builder.build()
    writer = OutputWriter(out_dir or Path("."), include_source=not options.no_source)
    stats = writer.stats(graph, index, parsed_files)
    written = writer.write_all(graph, index, parsed_files, root=root) if out_dir is not None else {}
    return AnalysisResult(stats, written, parsed_files, builder, time.monotonic() - started)


def _parser(root: Path, options: AnalysisOptions) -> CodebaseParser:
    return CodebaseParser(
        root,
        strip_prefix=options.strip_prefix,
        module_prefix=options.module_prefix,
        exclude_dirs=[*options.exclude_dir, STORE_DIRNAME],
        exclude_globs=options.exclude,
        max_file_bytes=options.max_file_bytes,
    )


# -- the store ----------------------------------------------------------------


class Store:
    """A ``.adventure-call/`` directory and the project root it describes."""

    def __init__(self, path: Path) -> None:
        self.path = Path(path).resolve()

    @property
    def root(self) -> Path:
        return self.path.parent

    @property
    def config_path(self) -> Path:
        return self.path / CONFIG_FILENAME

    def exists(self) -> bool:
        return self.config_path.is_file()

    # -- discovery -----------------------------------------------------------

    @classmethod
    def find(cls, start: Path | str | None = None) -> "Store":
        """The nearest store at or above ``start`` (default: the cwd)."""
        here = Path(start or os.getcwd()).resolve()
        if here.name == STORE_DIRNAME and (here / CONFIG_FILENAME).is_file():
            return cls(here)
        for directory in (here, *here.parents):
            candidate = directory / STORE_DIRNAME
            if (candidate / CONFIG_FILENAME).is_file():
                return cls(candidate)
        raise StoreError(
            f"no {STORE_DIRNAME}/ found at or above {here}; run 'adventure-call init' at the project root"
        )

    @staticmethod
    def default_root(start: Path | str | None = None) -> Path:
        """The git work tree containing ``start``, else ``start`` itself."""
        here = Path(start or os.getcwd()).resolve()
        try:
            top = subprocess.run(
                ["git", "rev-parse", "--show-toplevel"],
                cwd=here,
                capture_output=True,
                text=True,
                timeout=10,
            )
            if top.returncode == 0 and top.stdout.strip():
                return Path(top.stdout.strip()).resolve()
        except (OSError, subprocess.SubprocessError):
            pass
        return here

    # -- config --------------------------------------------------------------

    def load_options(self) -> AnalysisOptions:
        try:
            data = json.loads(self.config_path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            raise StoreError(f"unreadable {self.config_path}: {exc}") from None
        return AnalysisOptions.from_dict(data.get("options", {}))

    def save_options(self, options: AnalysisOptions) -> None:
        self.path.mkdir(parents=True, exist_ok=True)
        payload = {"adventure_call": __version__, "options": asdict(options)}
        self.config_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
        gitignore = self.path / ".gitignore"
        if not gitignore.exists():
            gitignore.write_text(_GITIGNORE, encoding="utf-8")

    # -- analysis ------------------------------------------------------------

    def update(self, options: AnalysisOptions | None = None) -> AnalysisResult | None:
        """Re-run the analysis into the store and refresh AGENTS.md."""
        from adventure_call.agents_doc import render_agents_md

        options = options or self.load_options()
        manifest = self._scan(options)
        result = analyse(self.root, options, self.path)
        if result is None:
            return None
        (self.path / MANIFEST_FILENAME).write_text(
            json.dumps(manifest, separators=(",", ":")) + "\n", encoding="utf-8"
        )
        (self.path / AGENTS_FILENAME).write_text(render_agents_md(), encoding="utf-8")
        return result

    def _scan(self, options: AnalysisOptions) -> dict[str, int]:
        parser = _parser(self.root, options)
        manifest: dict[str, int] = {}
        for path in parser.iter_source_files():
            try:
                manifest[parser.relative_path(path)] = path.stat().st_mtime_ns
            except OSError:
                continue
        return manifest

    def staleness(self) -> dict[str, list[str]]:
        """Source changes since the last analysis: modified, added, deleted.

        Empty when the store is current.  A store with no manifest (written by
        a different version) counts as wholly stale.
        """
        try:
            before: dict[str, int] = json.loads(
                (self.path / MANIFEST_FILENAME).read_text(encoding="utf-8")
            )
        except (OSError, ValueError):
            return {"modified": ["<no manifest>"]}
        now = self._scan(self.load_options())
        changes = {
            "modified": sorted(p for p, m in now.items() if p in before and before[p] != m),
            "added": sorted(p for p in now if p not in before),
            "deleted": sorted(p for p in before if p not in now),
        }
        return {k: v for k, v in changes.items() if v}
